name: Manually triggered workflow
on: 
 repository_dispatch:
  types:jianji
 

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Hello World
      run: |
        echo My name is P3TERX.
        echo Hello World!
